<a href="https://colab.research.google.com/github/HarryAI-6748/ml-project/blob/main/Ecommerce_Sales_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ecommerce Sales Data

In [3]:
import pandas as pd
import random

random.seed(42)

# Define data parameters
regions = ['North', 'South', 'East', 'West']
categories = ['Electronics', 'Clothing', 'Home & Garden', 'Sports', 'Books']
salespersons = ['Alice', 'Bob', 'Carol', 'David', 'Emma', 'Frank']

# Generate 200 sales transactions
ecc_data = {
    'transaction_id': range(1001, 1201),
    'region': [random.choice(regions) for _ in range(200)],
    'category': [random.choice(categories) for _ in range(200)],
    'salesperson': [random.choice(salespersons) for _ in range(200)],
    'sales_amount': [round(random.uniform(50, 5000), 2) for _ in range(200)],
    'customer_id': [random.randint(5000, 5100) for _ in range(200)]
}

ecc_df = pd.DataFrame(ecc_data)
print(ecc_df.head(10))
print(f"\nDataset shape: {ecc_df.shape}")

   transaction_id region     category salesperson  sales_amount  customer_id
0            1001  North  Electronics        Emma       4000.80         5075
1            1002  North        Books       Alice       3634.70         5084
2            1003   East  Electronics       David       4210.50         5025
3            1004  South  Electronics        Emma       4601.73         5054
4            1005  South     Clothing         Bob       4904.57         5014
5            1006  South     Clothing       Carol       2693.91         5069
6            1007  North       Sports       Alice       4539.30         5028
7            1008  North       Sports       Frank       2979.87         5082
8            1009   West       Sports       David       3331.85         5019
9            1010  North     Clothing       Alice        465.54         5034

Dataset shape: (200, 6)

Task 1: Basic Grouping and Single Aggregations

Calculating total sales amount for each region using groupby() and sum()

In [4]:
ecc_df.groupby('region')['sales_amount'].sum().reset_index()

  region  sales_amount
0   East      95189.81
1  North     135181.16
2  South     158977.36
3   West     109383.07

Counting the number of transactions for each product category using groupby() and count()

In [5]:
ecc_df.groupby('category')['sales_amount'].count().reset_index()

        category  sales_amount
0          Books            39
1       Clothing            42
2    Electronics            45
3  Home & Garden            43
4         Sports            31

Calculating the average sales amount per salesperson using groupby() and mean()

In [6]:
ecc_df.groupby('salesperson')['sales_amount'].mean().round(2).reset_index()

  salesperson  sales_amount
0       Alice       1998.43
1         Bob       2554.92
2       Carol       2454.37
3       David       2743.04
4        Emma       2493.46
5       Frank       2464.14

Sorting the regional sales results in descending order using sort_values(ascending=False) to identify the top-performing region

In [7]:
ecc_df.groupby('region')['sales_amount'].sum().sort_values(ascending = False).reset_index()

  region  sales_amount
0  South     158977.36
1  North     135181.16
2   West     109383.07
3   East      95189.81

Task 2: Multi-Column Grouping and Multiple Aggregations

Grouping by both region AND category to calculate total sales for each combination using: df.groupby(['region', 'category'])['sales_amount'].sum().reset_index()

In [8]:
ecc_df.groupby(['region', 'category'])['sales_amount'].sum().reset_index()

   region       category  sales_amount
0    East          Books      20027.53
1    East       Clothing      19926.20
2    East    Electronics      22791.55
3    East  Home & Garden      15949.08
4    East         Sports      16495.45
5   North          Books      42592.53
6   North       Clothing      18959.06
7   North    Electronics      38889.84
8   North  Home & Garden      19344.48
9   North         Sports      15395.25
10  South          Books      21007.68
11  South       Clothing      50878.36
12  South    Electronics      39229.63
13  South  Home & Garden      22592.00
14  South         Sports      25269.69
15   West          Books      20359.41
16   West       Clothing      16548.81
17   West    Electronics      13553.27
18   West  Home & Garden      33069.36
19   West         Sports      25852.22

For each salesperson, calculating three metrics simultaneously using the agg() method:
    Total sales ('sum')
    Average sales ('mean')
    Number of transactions ('count')

In [9]:
ecc_df.groupby('salesperson').agg({'sales_amount' : ['sum', 'mean'], 'transaction_id' : 'count'}).reset_index()# method 2

  salesperson sales_amount              transaction_id
                       sum         mean          count
0       Alice     43965.51  1998.432273             22
1         Bob     81757.41  2554.919063             32
2       Carol     68722.32  2454.368571             28
3       David    123436.64  2743.036444             45
4        Emma     82284.09  2493.457273             33
5       Frank     98565.43  2464.135750             40

In [10]:
ecc_df.groupby('salesperson')['sales_amount'].agg(['sum', 'mean', 'count']).reset_index()# method 1

  salesperson        sum         mean  count
0       Alice   43965.51  1998.432273     22
1         Bob   81757.41  2554.919063     32
2       Carol   68722.32  2454.368571     28
3       David  123436.64  2743.036444     45
4        Emma   82284.09  2493.457273     33
5       Frank   98565.43  2464.135750     40

Sorting the salesperson results by total sales in descending order to identify the top performer

In [11]:
y = ecc_df.groupby('salesperson')['sales_amount'].agg(['sum', 'count'])
y.sort_values(by = 'sum', ascending = False).reset_index().head(1)

  salesperson        sum  count
0       David  123436.64     45

Using .idxmax() on the grouped category sales to find which category has the maximum total revenue

In [12]:
ecc_df.groupby('category')['sales_amount'].sum().idxmax()

'Electronics'

Custom Aggregation and Complete Sales Report

Create a comprehensive sales analysis report:

Define a custom aggregation function that calculates the sales range (max - min) for each group:

In [13]:
def sales_range(x):
  return x.max() - x.min()

Applying this custom function along with standard aggregations to analyze sales by region:

In [14]:
ecc_df.groupby('region')['sales_amount'].agg(['sum', 'mean', 'min', 'max', sales_range]).reset_index()

  region        sum         mean     min      max  sales_range
0   East   95189.81  2213.716512  307.82  4758.46      4450.64
1  North  135181.16  2413.949286  110.71  4788.56      4677.85
2  South  158977.36  2789.076491  373.45  4983.33      4609.88
3   West  109383.07  2485.978864  203.60  4903.53      4699.93

Creating a final summary report that shows for each region:

    Total number of transactions (using customer_id with count)
    Total sales amount  
    Average transaction value

In [26]:
ecc_df.groupby('region').agg({
    'transaction_id' : 'count',
    'sales_amount' : ['sum', 'mean']
}).round(2).reset_index()

  region transaction_id sales_amount
                  count          sum     mean
0   East             43     95189.81  2213.72
1  North             56    135181.16  2413.95
2  South             57    158977.36  2789.08
3   West             44    109383.07  2485.98

The multilevel column structure takes input as key value pairs in which for each region, total counts of transactions, total sum of sales and the average of sales amount are displayed altogether which is possible because multiple aggregation functions are applied to one or more columns.

Single aggregations refer to applying a single function to one or more columns, or applying a list of functions without using a dictionary